export const img_rules: RegExp[] = [
  /^https?:\/\/[a-z0-9_.\/-]+.gif/,
  /^https?:\/\/counter.yadro.ru/,
  /^https?:\/\/counter.rambler.ru/,
  /^https?:\/\/ad.adriver.ru/,
  /^https?:\/\/awaps.yandex.ru/,
  /^https?:\/\/www.yandex.ru\/cycounter/,
  /^https?:\/\/ads.betweendigital.com/,
  /^https?:\/\/pagead2.googlesyndication.com/,
  /^https?:\/\/sync.rambler.ru/,
  /^https?:\/\/[a-z0-9_.-]+.doubleclick.net/,
  /^https?:\/\/[a-z0-9_.-]+.mail.ru\/k\?/,
  /^https?:\/\/[a-z0-9_.-]+scorecardresearch.com/,
  /^https?:\/\/www.tns-counter.ru/,
  /^https?:\/\/pixel.quantserve.com/,
  /^https?:\/\/ads.adfox.ru/,
  /^https?:\/\/pixel.mathtag.com/,
  /^https?:\/\/beacon.krxd.net/,
  /^https?:\/\/vk.com\/rtrg\?/,
  /^https?:\/\/syndication.twitter.com/,
  /^https?:\/\/[a-z0-9_.-]+.mobilebanner.ru/,
  /^https?:\/\/[a-z0-9_.-]+.gfycat.com/,
  /^https?:\/\/palacesquare.rambler.ru/ //ad
  ];
