export const db = [
    'an.yandex.ru',
    'ads.adfox.ru',
    'www.googletagmanager.com',
    'www.google-analytics.com',
    'hm.baidu.com',
    'push4site.com',
    'rum-static.pingdom.net',
    'vk.com/rtrg',
    'counter.yadro.ru',
    'connect.facebook.net',
    'stats.g.doubleclick.net',
    'mc.yandex.ru',
    'ads.pubmatic.com',
    'securepubads.g.doubleclick.net',
    'tag.digitaltarget.ru',
    'content.adriver.ru',
    'analytics.paddle.com'
];